
services:
    # Service for the Laravel application (PHP)
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: hr_system
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        ports:
          - 8000:8000

    # Service for the Nginx web server
    web:
        image: nginx:alpine
        container_name: hr-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    # Service for the MySQL database
    db:
        image: mysql:8.0
        container_name: hr-database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: hr_db
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: password
            MYSQL_USER: hr_user
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    # Service for Redis, a popular caching and queue service
    # redis:
    #     image: redis:alpine
    #     container_name: redis_cache
    #     restart: unless-stopped
    #     networks:
    #         - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_service
        restart: always
        ports:
            - 8082:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        networks:
            - app-network

# Define a Docker network for the containers to communicate with each other
networks:
    app-network:
        driver: bridge

# Define a volume to persist the database data
volumes:
    dbdata:
        driver: local

